App\Entity\Location:
    properties:
        city:
            - NotBlank: { groups: ['create', 'edit'] }
            - Length:
                min: 2
                max: 100
                groups: ['create', 'edit']
        country:
            - NotBlank: { groups: ['create', 'edit'] }
        latitude:
            - NotBlank: { groups: ['create', 'edit'] }
            - Type:
                type: numeric
                message: "Latitude must be a number."
                groups: ['create', 'edit']
            - Range:
                min: -90
                max: 90
                groups: ['create', 'edit']
        longitude:
            - NotBlank: { groups: ['create', 'edit'] }
            - Type:
                type: numeric
                message: "Longitude must be a number."
                groups: ['create', 'edit']
            - Range:
                min: -180
                max: 180
                groups: ['create', 'edit']